### PR TITLE
Fix return clause parallel

### LINKED ISSUE #615: Undue materialization
count(let $i := parallelize(1 to 1000) return $i)

No materialization should happen here.

### PR DESCRIPTION
**Pull request by ghislainfourny**
Fixes #615 

This should help with your demo.

Enjoy!

### CODE REVIEW

File: src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java [hunk 1]
```diff
@@ -63,18 +65,75 @@ public ReturnClauseSparkIterator(
...
-            throw new JobWithinAJobException(
-                    "A return clause expression cannot produce a big sequence of items for a big number of tuples, as this would lead to a data flow explosion.",
-                    getMetadata()
-            );
+            if (this.child.isDataFrame())
+                throw new JobWithinAJobException(
+                        "A return clause expression cannot produce a big sequence of items for a big number of tuples, as this would lead to a data flow explosion.",
+                        getMetadata()
+                );
+            this.tupleContext = new DynamicContext(this.currentDynamicContextForLocalExecution); // assign current
```
Comment (CanBerker) [inline src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java:73]: this.currentDynamicContextForLocalExecution should be used only in local methods. This should probably be 'context' variable

File: src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java [hunk 2]
```diff
@@ -63,18 +65,75 @@ public ReturnClauseSparkIterator(
...
+    @Override
+    public Dataset<Row> getDataFrame(DynamicContext context) {
+        RuntimeIterator expression = this.children.get(0);
+        if (expression.isRDD()) {
+            if (this.child.isDataFrame())
+                throw new JobWithinAJobException(
+                        "A return clause expression cannot produce a big sequence of items for a big number of tuples, as this would lead to a data flow explosion.",
+                        getMetadata()
+                );
+            this.tupleContext = new DynamicContext(this.currentDynamicContextForLocalExecution); // assign current
```
Comment (CanBerker) [inline src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java:109]: Same comment

File: src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java (hunk 1 above)
Comment (ghislainfourny) [reply src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java]: Yes, good catch and that was indeed one of the issues. All is fixed now.

File: src/main/java/org/rumbledb/expressions/flowr/ReturnClause.java [hunk 3]
```diff
@@ -46,10 +46,19 @@ public Expression getReturnExpr() {
...
+        }
+        if (this.returnExpr.getHighestExecutionMode(visitorConfig).isRDD()) {
+            this.highestExecutionMode = ExecutionMode.RDD;
+            return;
+        }
+        if (this.returnExpr.getHighestExecutionMode(visitorConfig).isDataFrame()) {
+            this.highestExecutionMode = ExecutionMode.DATAFRAME;
+            return;
+        }
+        this.highestExecutionMode = ExecutionMode.LOCAL;
```
Comment (CanBerker) [inline src/main/java/org/rumbledb/expressions/flowr/ReturnClause.java:61]: Very nicely handled. I felt like I would be prone to making a mistake here :)

Comment (ghislainfourny) [reply src/main/java/org/rumbledb/expressions/flowr/ReturnClause.java:61]: This was not a mistake -- this was just not implemented yet (because not trivial). :)
